# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 16:17
from __future__ import unicode_literals

from django.db import migrations
from ..data_migrations import create_actions


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170123_1606'),
    ]

    operations = [
        migrations.RunPython(create_actions)
    ]
