# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170123_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statecontrollerdata',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='statecontroller',
            name='task_id',
            field=models.CharField(blank=True, help_text='Task ID that this controller is currently running.', max_length=64, null=True, verbose_name='Task ID'),
        ),
    ]
